apiVersion: apps/v1
kind: Deployment
metadata:
  name: water-usage-service
  namespace: watermonitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: water-usage-service
  template:
    metadata:
      labels:
        app: water-usage-service
    spec:
      containers:
        - name: parcel-trace-service
          image: gaitwatermonitor/watermonitor:waterusageservicelatest
          imagePullPolicy: Always
          ports:
            - containerPort: 8043
              protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: watermonitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: gaitwatermonitor/watermonitor:gatewaylatest
          imagePullPolicy: Always
          ports:
            - containerPort: 9092
              protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: watermonitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: gaitwatermonitor/watermonitor:userservicelatest
          imagePullPolicy: Always
          ports:
            - containerPort: 8044
              protocol: TCP